[package]
name = "slimebot"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
chrono = { version = "0.4.31", features = ["serde"] }
config = "0.13.3"
dotenv = "0.15.0"
# espeakng = "0.2.0"
hostname = "0.3.1"
indoc = "2.0.4"
log = "0.4.20"
poise = "0.5.5"
reqwest = { version = "0.11.18", features = ["blocking"] }
scraper = "0.17.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
songbird = { version = "0.3.2", features = ["serenity-rustls", "yt-dlp"] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.17", features = ["std", "env-filter"] }
tracing-unwrap = "0.10.0"
