[package]
name = "slimebot"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.74"
async-trait = "0.1.73"
dotenv = "0.15.0"
log = { version = "0.4.20", features = ["std"] }
poise = "0.5.5"
reqwest = { version = "0.11.18", features = ["blocking"] }
scraper = "0.17.1"
tokio = { version = "1.32.0", features = ["rt", "macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-layer-discord = "0.1.3"
tracing-subscriber = "0.3.17"
