# example slimebot compose.toml
# IMPORTANT: docker compose will accept `compose.yaml`, NOT `example-compose.yaml`

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: #mongodb root username
      MONGO_INITDB_ROOT_PASSWORD: #mongodb root password
    ports:
      - 27017:27017 #mongodb port
  
  bot:
    build: .
    restart: always
    volumes:
      - ./.env:/.env #mount .env to /.env in the container
      - ./slimebot.toml:/slimebot.toml #mount slimebot.toml to /slimebot.toml in the container
    ports:
      - 443:443