name: CI

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Install rust
      uses: dtolnay/rust-toolchain@nightly

    - name: Cache rust
      uses: Swatinem/rust-cache@v2

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
